name: keep_motive
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0-149.3.beta

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  json_annotation: ^4.8.1
  animations: ^2.0.7
  share_plus: ^10.0.2
  cupertino_icons: ^1.0.8
  firebase_core: ^2.15.0  # Add this line
  firebase_analytics: ^10.3.0  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.6.1
  google_fonts: ^4.0.4
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "icons/keep_motive_icon_512.png"

flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/quotes.json
